### ISSUE TITLE
Hold a Pass - Designs

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#329]
#### Description:

For the hold pass timer feature, we will need to create and update some designs in the DUP Public and Admin sides.

#### Acceptance Criteria:

**Public**
- [x] Update `Facilities` button to say `Back` and appear in a blue more button-y style (add wireframe link to herE: https://github.com/bcgov/parks-reso-public/issues/333)
- [ ] Update `Next` button to say `Reserve` (Add wireframe link to this Dev ticket: https://github.com/bcgov/parks-reso-public/issues/330)
- [x] Design timer for the booking page (gets pinned) (add wireframe link to this dev ticket: https://github.com/bcgov/parks-reso-public/issues/330)
- [ ] Design pop-up message for when someone tries to navigate away ("ARE YOU SURE?") (https://github.com/bcgov/parks-reso-public/issues/334)
- [ ] Design a pop-up message for when the timer runs out and user is notified that their pass is no longer held. ("TIME'S UP") (https://github.com/bcgov/parks-reso-public/issues/334)
- [ ] Design a sold-out toast message that's user friendly and informative, and with the option to go back. https://github.com/bcgov/parks-reso-public/issues/335
- [ ] Update wording on the booking page and home page to notify visitors of the new timer feature https://github.com/bcgov/parks-reso-public/issues/338

~**Admin**~ NO LONGER NEED THIS - ADDED TO ICEBOX
- [ ] ~add to capacity bar with "passes currently held" https://github.com/bcgov/parks-reso-admin/issues/351~

#### Design

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

#### Notes:
- 
-
