### ISSUE TITLE
Designs: Facility-specific success confirmation page -> Garibaldi - Rubble Creek, Cheakamus, and Diamondhead

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#399]
#### Description:

This ticket is to create any relevant designs for facility specific messaging on the Garibaldi confirmation pages. Web confirmation page will require moving some components around on the page as well as adding in icons, text and links to convey message. 

#### Acceptance Criteria:

- [ ] designs for facility specific messaging on Garibaldi Rubble Creek and Cheakamus facilities confirmation pages are in figma and linked [here](https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-26578&t=DfCaMrcNVjCTrR3f-1)

#### Development Checklist:

**Rubble Creek Confirmation Page**
- [ ] Success! Your reservation is complete title will now span across the top of the page
- [ ] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [ ]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
  - [ ]  Be prepared. Get to know the AdventureSmart’s 3Ts. (Adventure smart link: https://www.adventuresmart.ca/the-three-ts/ )
  - [ ]  Check the park page for advisories. (Park page link: https://bcparks.ca/garibaldi-park/ )
  - [ ]  Create a trip plan.  (trip plan link: https://www.adventuresmart.ca/trip-plan-app/)
  - [ ] Be Bear Aware. Avoid or stow attractants to help avoid encounters. (link to bear aware: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
  - [ ] Stay on the trail. Shortcutting endangers other visitors with rolling debris.
  - [ ] Pack sufficient water or be prepared to treat fresh water. There are no significant water sources before the 7 km mark on the trail.
  - [ ] BC Parks strongly advises against summitting Black Tusk.
  - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366) with are a max of 36 height or width, but they are set in a frame that is 48x48px to provide sufficient space around them
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
     - [ ] Respect other park users. Do not play music out loud.  
     - [ ] There are no garbage cans along the trail. Understand your responsibility to #LeaveNoTrace by packing out anything you pack in.  (Leave no trace link: https://www.youtube.com/watch?v=zcktbVamiQg&t=1s&ab_channel=GovernmentofBC)
     - [ ] Pets are not permitted in Garibaldi Park.
      - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366) with are a max of 36 height or width, but they are set in a frame that is 48x48px to provide sufficient space around them
    - [ ]  -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

**Cheakamus Confirmation Page**
- [ ] Success! Your reservation is complete title will now span across the top of the page
- [ ] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [ ]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
  - [ ]  Be prepared. Create a trip plan.  (trip plan link: https://www.adventuresmart.ca/trip-plan-app/) and get to know the AdventureSmart’s 3Ts. (Adventure smart link: https://www.adventuresmart.ca/the-three-ts/ )
  - [ ]  Check the park page for advisories. (Park page link: https://bcparks.ca/garibaldi-park/ )
  - [ ] Be Bear Aware. Avoid or stow attractants to help avoid encounters. (Bear Aware Link: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
  - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366), exception for the triangle check the park page icon this is reduced to 34x34 as it appears larger than the rest.
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
     - [ ] This area of Garibaldi Park has special cultural significance to local Indigenous communities. Please respect the land.
     - [ ] Biking is permitted to Cheakamus Lake and Singing Creek but not Helm Creek. Use bike-specific paths when available, and be considerate of hikers.
     - [ ] Respect other park users. Do not play music out loud.  
     - [ ] There are no garbage cans along the trail. Understand your responsibility to #LeaveNoTrace by packing out anything you pack in.  (Leave no trace link: https://www.youtube.com/watch?v=zcktbVamiQg&t=1s&ab_channel=GovernmentofBC)
     - [ ] Pets are not permitted in Garibaldi Park.   
   - [ ]  Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366) with are a max of 36 height or width, but they are set in a frame that is 48x48px to provide sufficient space around them
 -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

**Diamondhead Confirmation Page**
- [ ] Success! Your reservation is complete title will now span across the top of the page
- [ ] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [ ]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
  - [ ]  Be prepared.  Create a trip plan.  (trip plan link: https://www.adventuresmart.ca/trip-plan-app/) and get to know the AdventureSmart’s 3Ts. (Adventure smart link: https://www.adventuresmart.ca/the-three-ts/ )
  - [ ]  Check the park page for advisories. (Park page link: https://bcparks.ca/garibaldi-park/ )
  - [ ] Be Bear Aware. Avoid or stow attractants to help avoid encounters. (Bear Aware Link: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
  - [ ]Pack enough water, or be prepared to treat fresh water. There are no significant water sources beyond the 5 km mark on the trail until you reach Elfin Lakes at 11 km.
    - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366) with are a max of 36 height or width, but they are set in a frame that is 48x48px to provide sufficient space around them
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
     - [ ] Biking is permitted to Elfin Lakes, but not to Rampart Ponds. Use bike-specific paths when available, and be considerate of hikers.
     - [ ]  Respect other park users. Do not play music out loud.  
     - [ ] There are no garbage cans along the trail. Understand your responsibility to #LeaveNoTrace by packing out anything you pack in.  (Leave no trace link: https://www.youtube.com/watch?v=zcktbVamiQg&t=1s&ab_channel=GovernmentofBC)
     - [ ] Pets are not permitted in Garibaldi Park.
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366) with are a max of 36 height or width, but they are set in a frame that is 48x48px to provide sufficient space around them
 -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

#### Dependencies

- Blocked by
- Blocking #401 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by ndelraye** [comment]
waiting for trail description links from @MarshallHenson for Cheakamus and Diamondhead

**Comment by MarshallHenson** [comment]
text has been reviewed by the web team & regional staff. good to go, @ndelraye

**Comment by ndelraye** [comment]
updates are done as per Marshalls edits, new icons are needed for the following:
Stay on the trail. Shortcutting endangers other visitors with rolling debris.
Pack sufficient water or be prepared to treat fresh water. There are no significant water sources before the 7 km mark on the trail.
BC Parks strongly advises against summitting Black Tusk.
Biking is permitted to Cheakamus Lake and Singing Creek but not Helm Creek. Use bike-specific paths when available, and be considerate of hikers.
Biking is permitted to Elfin Lakes, but not to Rampart Ponds. Use bike-specific paths when available, and be considerate of hikers.
This area of Garibaldi Park has special cultural significance to local Indigenous communities. Please respect the land.
Pack enough water, or be prepared to treat fresh water. There are no significant water sources beyond the 5 km mark on the trail until you reach Elfin Lakes at 11 km.
