### ISSUE TITLE
Designs: Facility-specific success confirmation page -> Golden Ears - Allouette boat launch & south beach, Gold Creek and West Canyon

### ISSUE THREAD

**Issue by meyerdarcie** [bcgov/parks-reso-public#400]
#### Description:

This ticket is to create any relevant designs for facility specific messaging on the Golden Ears confirmation pages. Web confirmation page will require moving some components around on the page as well as adding in icons, text and links to convey message. 

#### Acceptance Criteria:

- [ ] designs for facility specific messaging on Golden Ears Alouette lake boat launch, South Beach, Gold Creek, and West Canyon confirmation pages are in figma and linked [here](https://www.figma.com/design/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?node-id=4759-26578&t=DfCaMrcNVjCTrR3f-1)

#### Development Checklist:

**Alouette Lake Boat Launch & Alouette Lake South Beach Access Confirmation Page**
- [x] Success! Your reservation is complete title will now span across the top of the page
- [x] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [x]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
   - [ ]  Check the park page for advisories. (Park page link: https://bcparks.ca/golden-ears-park/ )
  - [ ]  Be Bear Aware. Avoid or stow attractants to help avoid encounters. (Bear Aware link: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
  - [ Alouette Lake has a steep drop off. Supervise children and wear a life jacket.
  - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366), exception for the triangle check the park page icon this is reduced to 34x34 as it appears larger than the rest.
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
          - [ ] Dogs are allowed in select beach areas, but must be kept on a leash. (link to select beach areas: https://bcparks.ca/golden-ears-park/#park-activity-container)
          - [ ] Smoking and alcohol consumption are not permitted on the beach.
          - [ ] Golden Ears Park only recycles refundable containers (???marshall to clarify what this is). For other recyclables, please take them home to recycle.
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366)
 -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

**Gold Creek Confirmation Page**
- [ ] Success! Your reservation is complete title will now span across the top of the page
- [ ] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [ ]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
   - [ ] Be prepared. Familiarize yourself with AdventureSmart's 3Ts. (link to adventure smart: https://www.adventuresmart.ca/the-three-ts/) 
   - [ ] Check the park page for advisories. (Park page link: https://bcparks.ca/golden-ears-park/ )
   - [ ] Create a trip plan. (link to trip plan: https://www.adventuresmart.ca/trip-plan-app/)
  - [ ]  Be Bear Aware. Avoid or stow attractants to help avoid encounters. (Bear Aware link: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366), exception for the triangle check the park page icon this is reduced to 34x34 as it appears larger than the rest.
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
          - [ ] Dogs must be kept on leash on North Beach.
          - [ ] Smoking and alcohol consumption are not permitted on the beach.
          - [ ] Campfires are not permitted in the backcountry.
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366)
 -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

**West Canyon Confirmation Page**
- [ ] Success! Your reservation is complete title will now span across the top of the page
- [ ] The blue reservation details box moves to the left side of the page under the under the your reservation number
- [ ]  If a QR code is enabled the save or print text and QR code will display below the blue details box on the left side of the page
- [ ] The print button moves under the blue reservation details box
- [ ] Left side include unique text and icons based on park and facility 
- [ ] New heading Safety information is added and includes the following text and related icons, all links will open in a new window:
   - [ ] Be prepared. Familiarize yourself with AdventureSmart's 3Ts. (link to adventure smart: https://www.adventuresmart.ca/the-three-ts/) 
   - [ ] Check the park page for advisories. (Park page link: https://bcparks.ca/golden-ears-park/ )
   - [ ] Create a trip plan. (link to trip plan: https://www.adventuresmart.ca/trip-plan-app/)
  - [ ]  Be Bear Aware. Avoid or stow attractants to help avoid encounters. (Bear Aware link: https://bcparks.ca/plan-your-trip/visit-responsibly/wildlife-safety/#bears)
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366), exception for the triangle check the park page icon this is reduced to 34x34 as it appears larger than the rest.
 - [ ] 2nd New heading is Visitor guidelines is added and included the following text and related icons, all links will open in a new window
          - [ ] There are no garbage cans along the trail. Understand your responsibility to #LeaveNoTrace by packing out anything you have packed in. (NEED LINK FROM MARSHALL)
          - [ ] Campfires are not permitted in the backcountry.
   - [ ] Icons are FontAwesome “Classic Regular” icon collection Pro, Large (36px) (colour #003366)
 -  [ ]  Final heading Next steps will include the following text and numbering:
    - [ ]  1. You will receive your pass by email soon. If you do not receive an email, please contact parkinfo@gov.bc.ca for assistance. (link to parkinfo: mailto:parkinfo@gov.bc.ca)
    - [ ] 2. Print your pass or save a copy to your phone.
    - [ ]  3. If you no longer need your reservation, please cancel it using the link in your confirmation email.

#### Dependencies

- Blocked by
- Blocking #402 

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by ndelraye** [comment]
Marshall to clarify what ??? mean on the recycling item on Alouette lake 
Marshall to add link to leave no trace for West Canyon

**Comment by Dianadec** [comment]
Notes from July 11 mtg with Marshall & Brett: 
- Golden ears will be delayed - won't action it this summer.

**Comment by LindsayMacfarlane** [comment]
Hi @MarshallHenson - what are your thoughts on dusting this ticket off? During recent testing of DUP, I noticed that not all of our confirmation messages are the same. Could be a good opportunity to bring in some consistency.

**Comment by MarshallHenson** [comment]
I need to engage with regional staff to get input on the copytext. Email sent out on Dec 11.

**Comment by LindsayMacfarlane** [comment]
Hi @MarshallHenson - any feedback form regional staff on the copy? Would love to get this wrapped up :)

**Comment by MarshallHenson** [comment]
https://bcgov.sharepoint.com/:w:/r/teams/031072/Shared%20Documents/%5BProduct%5D%20Parking%20Services/DUP%20Reso%20Site%20Content/Golden%20Ears%20Confirmation%20Page.docx?d=wdd7c4517717e4cb8b86f13d672f23205&csf=1&web=1&e=b4pwco 

Ready to go!

**Comment by meredithom** [comment]
Figma designs have been updated based on the sharepoint document! 

I don't see anything in this ticket about updating the email messaging and I noticed it's slightly out of sync now. Not sure if that's been captured somewhere else or if we want to include it in this one.

**Comment by MarshallHenson** [comment]
The email messaging is currently split by vehicle / trail passes, not by facility. Last time we discussed it, there was some question as to whether we would continue with GC Notify long-term so we decided to stick with the simplest version of email control (avoiding an abundance of templates)

**Comment by MarshallHenson** [comment]
note: we have removed "information" from the safety title on all the other designs

**Comment by LindsayMacfarlane** [comment]
Thank you @meredithom ! I've added the figma link to the implementation ticket and made reference to remove the "information" from the safety tile.
